### ISSUE TITLE
container mysql is unhealthy

### ISSUE THREAD

**Issue by openncomp** [nixys/nxs-support-bot#1]
Приветствую.
Пробую мигрировать с _**nxs-chat-srv**_ на _**nxs-support-bot**_.

Заполнил _**.deploy/docker-compose/.env_migrate**_ запускаю _**docker compose -f docker-compose-migrate.yml up -d**_, процесс загрузки проходит нормально:
![изображение](https://github.com/nixys/nxs-support-bot/assets/92163803/4ace22ff-bf1d-4b79-9416-2762b118bf9a)
После этого при запуске получаю ршибку:
![изображение](https://github.com/nixys/nxs-support-bot/assets/92163803/1c3d2c01-d07b-4450-a918-6d24cec0f359)
На этом процесс миграции, как я понимаю, прерывается.

**Comment by openncomp** [comment]
Есть мысль, а нужно ли иметь заполненный _**.deploy/docker-compose/.env**_ на этом этапе? Т.к. я этого не делал и он остался по-умолчанию.

**Comment by openncomp** [comment]
Заполнил _**.deploy/docker-compose/.env**_, но ситуация не поменялась, при повторном запуске миграции получаю:
![изображение](https://github.com/nixys/nxs-support-bot/assets/92163803/331189e5-9599-4553-a923-67e0f3bf96da)

**Comment by openncomp** [comment]
_**Docker ps**_:
![изображение](https://github.com/nixys/nxs-support-bot/assets/92163803/62196f1c-e0dc-43f7-93b3-e71a451f333d)

**Comment by AndreiMuvila** [comment]
Добрый день.
Есть ли что то в логах у контейнера или он падает молча?

**Comment by openncomp** [comment]
> Добрый день. Есть ли что то в логах у контейнера или он падает молча?

Вот что выдает _**docker logs mysql**_:
`Fatal glibc error: CPU does not support x86-64-v2`

Разворачиваю в ВМ Proxmox с процессором kvm64.
Сейчас попробую сменить ЦП на хостовый и повторить действия.

**Comment by AndreiMuvila** [comment]
> Разворачиваю в ВМ Proxmox с процессором kvm64.
> Сейчас попробую сменить ЦП на хостовый и повторить действия.

Вероятно это решит проблему.

**Comment by openncomp** [comment]
Да, после смены типа процессора у ВМ на хостовый ситуация поменялась, но контейнер mysql все еще не запускается.
Вот что выдает лог:
`error: database is uninitialized and password option is not specified
  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD`

Конфиг _**.deploy/docker-compose/.env_migrate**_ заполнен актуальными данными из конфига _**nxs-chat-srv.conf**_, но конфиг _**.deploy/docker-compose/.env**_ оставлен незаполненным.

**Comment by AndreiMuvila** [comment]
> Вот что выдает лог:
>` error: database is uninitialized and password option is not specified You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD`
> 
> Конфиг .deploy/docker-compose/.env_migrate заполнен актуальными данными из конфига nxs-chat-srv.conf, но конфиг .deploy/docker-compose/.env оставлен незаполненным.

Рутового пароля не хватает. Стоит указать требуемые параметры в `.deploy/docker-compose/.env`.

**Comment by openncomp** [comment]
Уточните, пожалуйста по заполнению конфига _**.deploy/docker-compose/.env**_.
В секции
_**# Docker compose options**_
значение
_**MYSQL_ROOT_PASSWORD=**_ - что именно должно тут задаваться, пароль новой БД или той, с которой идет миграция?

Также в секции
_**# Options block mysql**_ - указываем данные новой БД или старой, с которой мигрируем?

**Comment by openncomp** [comment]
Заполнил _**.deploy/docker-compose/.env**_ данными, такими же как и _**.deploy/docker-compose/.env_migrate**_, снова выполнил _**docker compose -f docker-compose-migrate.yml up -d**_ и теперь все контейнеры запустились, а бот успешно подключился к моему Redmine.

Спасибо большое за поддержку и обновление данного проекта!
Далее буду пробовать функционал и предлагать улучшения!

**Comment by AndreiMuvila** [comment]
В ` .deploy/docker-compose/.env` все что описывает новую версию. Требуемые параметры тоже там нужно указать.
В `.deploy/docker-compose/.env_migrate` данные для подключения к контейнерам старой версии и к новым. Чтобы перегрузить из старой версии бота в новую все нужные данные  .

**Comment by AndreiMuvila** [comment]
> Заполнил .deploy/docker-compose/.env данными, такими же как и .deploy/docker-compose/.env_migrate, снова выполнил docker compose -f docker-compose-migrate.yml up -d и теперь все контейнеры запустились, а бот успешно подключился к моему Redmine.

Хорошо, надеюсь миграция прошла успешно.
