### ISSUE TITLE
Возможна ли работа двух разных чат-ботов?

### ISSUE THREAD

**Issue by gr1ff0n** [nixys/nxs-support-bot#11]
В целях реализации разделения внутреннего и внешнего контуров приёма задач возник вопрос о возможности подключения второго бота для приёма задач от внешних организаций. Как-то возможно это реализовать текущим функционалом?
Или в таком случае лучше организовать второй редмайн с отдельным ботом?

**Comment by AndreiMuvila** [comment]
Мы не реализовывали возможность работы бота с двумя системами задач одновременно. Для такого разделения мы используем отдельные проекты с настроенными правами доступа.

Возможно вас тоже такой вариант устроит, но если нет, то придется поднимать второй редмайн и бота.

**Comment by gr1ff0n** [comment]
Отлично! Хорошая идея! Спасибо!

**Comment by AndreiMuvila** [comment]
Рад был помочь. Тикет закрываю.
