### ISSUE TITLE
Запуск бота в docker

### ISSUE THREAD

**Issue by v0van4eg** [nixys/nxs-support-bot#13]
Здравствуйте, этот вопрос уже поднимался, но ответа на него никто не дал, поэтому подниму её раз.
ОС - Debian-12
Docker version 20.10.24+dfsg1, build 297e128

При запуске docker-compose up возникают следующие ошибки:
WARNING: Some services (supportbot) use the 'configs' key, which will be ignored. Compose does not support 'configs' configuration - use `docker stack deploy` to deploy to a swarm.

Далее следующая ошибка сыпется в бесконечном режиме
supportbot    | {"details":"config error: open /app.conf: no such file or directory","level":"error","msg":"ctx init","time":"2024-01-18T11:26:16Z"}

Вопрос всё тот же, возможно ли как-то запустить бота? Какие системные требования к нему?

**Comment by AndreiMuvila** [comment]
Здравствуйте. 

Особых системных требований нет. 

Насколько мне известно в новых версиях Docker используется команда вида `docker compose up`, так как compose встроили внутрь.

Уточните, пожалуйста, какая версия docker-compose у вас установлена?

**Comment by v0van4eg** [comment]
### Версия
# docker-compose -v
docker-compose version 1.29.2, build unknown

не получается никак
#docker compose up
docker: 'compose' is not a docker command.
Где-то вычитал, что секцию configs надо изменить на secrets. Сделал так, варнинг исчез, но ошибка осталась.

**Comment by AndreiMuvila** [comment]
Возможно стоит обновить пакеты докера. Последняя версия композа сейчас `2.24.1`.

**Comment by v0van4eg** [comment]
Спасибо, так и есть, версия, которая идёт в стандартных репозиториях дебиана и убунты очень устаревшая, даже в самых свежих релизах. Docker необходимо устанавливать отдельно. Попробовал на Debian и на Ubuntu и всё заработало.

sudo apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
apt-cache policy docker-ce
sudo apt install docker-ce

Как я понял, docker-compose не используется
Бот запускается командой $ docker compose up

Всем спасибо, вопрос решился ))
