### ISSUE TITLE
Missing app.conf but it's there...

### ISSUE THREAD

**Issue by acosonic** [nixys/nxs-support-bot#6]
output of docker compose:
```
supportbot    | config error: open /app.conf: no such file or directory
supportbot exited with code 1

```
output of docker ps
```
CONTAINER ID   IMAGE                             COMMAND                  CREATED         STATUS                         PORTS                 NAMES
7e5602edf6b3   nixyslab/nxs-support-bot:latest   "/app -c /app.conf"      6 minutes ago   Restarting (1) 3 seconds ago                         supportbot
387b57b8a656   percona:8                         "/docker-entrypoint.…"   6 minutes ago   Up 2 minutes (healthy)         3306/tcp, 33060/tcp   mysql
1fb40f4b4434   bitnami/redis:latest              "/opt/bitnami/script…"   6 minutes ago   Up 2 minutes                   6379/tcp              redis

```

**Comment by AndreiMuvila** [comment]
Hello.

In the current version, the path to the configuration file in the container is as follows: `/nxs-support-bot.conf`. This file is generated automatically.

To configure, modify the `docker-compose.yml` file on the path `.deploy/docker-compose` and execute command: `docker-compose up -d` .

If you use Kubernetes, you need to configure in files along the `.deploy/kubernetes` path.

**Comment by acosonic** [comment]
No it's on docker... What's weird, after system reboot it started working as expected... It was fresh docker installation on Ubuntu 20.04

**Comment by AndreiMuvila** [comment]
Since no additional questions have been received, we close this task.

**Comment by v0van4eg** [comment]
Поднимаю вопрос. Всё то же самое, невозможно запустить
