### ISSUE TITLE
Displaying archived projects

### ISSUE THREAD

**Issue by acosonic** [nixys/nxs-support-bot#7]
Archived projects should not be displayed

**Comment by borisershov** [comment]
What projects do you mean? 🤔

**Comment by acosonic** [comment]
When /issue_create is called...  And you click Projects in Telegram, it displays all projects instead of just active ones...

**Comment by borisershov** [comment]
Ok, thanks for information!

@AndreiMuvila, can you check this on our testing environment?

**Comment by AndreiMuvila** [comment]
Hello.

Please, make a request like `https://REDMINE_HOST/projects/REDMINE_PROJECT_IDENTIFIER.json` to the archive project that is displayed incorrectly, and send us the contents of the `status` field

**Comment by acosonic** [comment]
Sorry it is working properly, there is 220 projects, 54 are active on Redmine where I tested.
